using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieApi.Models.Entities;

/// <summary>
/// Represents an actor entity with basic information such as name, birth year,
/// and the collection of movies the actor has acted in.
/// </summary>
public class Actor
{
	/// <summary>
	/// Primary key for the actor. Value is generated by the database.
	/// </summary>
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-Increment for primary key
	public int Id { get; set; }

	/// <summary>
	/// Name of the actor. Maximum length is 50 characters.
	/// </summary>
	[MaxLength(50)]
	public string Name { get; set; } = null!;

	/// <summary>
	/// Birth year of the actor. Must be between 1850 and 2500.
	/// </summary>
	[Range(1850, 2500)]
	public int BirthYear { get; set; }

	/// <summary>
	/// Navigation property representing the collection of <see cref="Movie"/> entities
	/// associated with this actor in a many-to-many relationship.
	/// </summary>
	public ICollection<Movie> Movies { get; set; }
}
