using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieApi.Models.Entities;

/// <summary>
/// Represents detailed information about a movie.
/// This entity has a one-to-one relationship with the <see cref="Movie"/> entity.
/// </summary>
public class MovieDetails
{
	/// <summary>
	/// Gets or sets the unique identifier for the movie details.
	/// This is the primary key and is auto-generated by the database.
	/// </summary>
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-Increment for primary key
	public int Id { get; set; }

	/// <summary>
	/// Gets or sets the foreign key to the associated <see cref="Movie"/>.
	/// </summary>
	public int? MovieId { get; set; }

	/// <summary>
	/// Gets or sets the synopsis of the movie.
	/// Maximum length is 400 characters.
	/// </summary>
	[MaxLength(400)]
	public string Synopsis { get; set; } = null!;

	/// <summary>
	/// Gets or sets the language of the movie.
	/// Maximum length is 50 characters.
	/// </summary>
	[MaxLength(50)]
	public string Language { get; set; } = null!;

	/// <summary>
	/// Gets or sets the Budget of the movie.
	/// The Budget value must be between 0 and 500,000,000$.
	/// </summary>
	[Range(0, 500000000)]
	public int Budget { get; set; }

	/// <summary>
	/// Navigation property for the associated <see cref="Movie"/>.
	/// </summary>
	public Movie? Movie { get; set; } = null!;

}
