using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieApi.Models.Entities;

/// <summary>
/// Represents a review for a movie, including reviewer information, comment, and rating.
/// </summary>
public class Review
{
	/// <summary>
	/// Primary key for the review. Value is generated by the database.
	/// </summary>
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-Increment for primary key
	public int Id { get; set; }

	/// <summary>
	/// Foreign key to the associated <see cref="Movie"/> entity. 
	/// A review must be associated with a <see cref="Movie"/>.
	/// </summary>
	[Required]
	public int MovieId { get; set; }

	/// <summary>
	/// Name of the reviewer. Maximum length is 50 characters.
	/// </summary>
	[MaxLength(50)]
	public string ReviewerName { get; set; } = null!;

	/// <summary>
	/// Review comment text. Maximum length is 200 characters.
	/// </summary>
	[MaxLength(200)]
	public string Comment { get; set; } = null!;

	/// <summary>
	/// Rating given by the reviewer. Must be between 1 and 5.
	/// </summary>
	[Range(1, 5)]
	public int Rating { get; set; }

	/// <summary>
	/// Navigation property for the related <see cref="Movie"/> entity.
	/// </summary>
	[ForeignKey(nameof(MovieId))]
	public Movie Movie { get; set; } = null!;
}
